<?php

namespace App\Services;

use App\Models\SendToType;
use App\Models\Url;
use App\Models\Subscriber;
use App\Models\SentMessage;
use App\Services\GenerateReviewUrlService;
use Twilio\Rest\Client;

/**
 * This service is designed to be called to send a single message
 */
class SmsService
{
    // public Client $client;
    protected $genReview;
    protected $client;

    public function __construct(GenerateReviewUrlService $gr)
    {
        $this->genReview = $gr;
        // $this->client = $client;
    }

    /**
     * Contains params for message contents, one or more sendToTypes
     * @param $header: Message header to be displayed first
     * @param $body: Message body to be displayed second
     * @param $sendToTypes: array of kv pairs where values indicate to be sent
     * @param $url: A previously generated and stored shortened url.
     * for reviews, it would be generated by SendReviewText job handler,
     * for campaigns, it would be generated by 
     * 
     * @return json response
     */
    public static function send(string $header, string $body, mixed $sendToTypes, string $url, int $businessId, string $reviewerNo=null)
    {
        try {
            // Get Twilio keys
            $account_id = getenv('TWILIO_SID');
            $auth_tok = getenv('TWILIO_TOKEN');
            $twilio_num = getenv('TWILIO_FROM');

            $client = new Client($account_id, $auth_tok);

            // Handle retrieving #'s from sendToType
            // \Log::info($sendToTypes);

            if (getenv('APP_ENV') === 'local') $reviewerNo = "+14352224432";

            if ($sendToTypes === 'Review Invite' && $reviewerNo !== null) {
                $sendToSubscriber = Subscriber::where(['phoneNumber' => $reviewerNo, 'businessId' => $businessId, 'subscribed' => 1])->firstOrFail();

                $shortUrl = !Url::where('fullUrl', $url)->exists() ? self::handleNewUrl($url, $reviewerNo) : Url::where('fullUrl', $url)->get()->shortUrl;

                $client->messages->create($reviewerNo, [
                    'from' => $twilio_num,
                    'body' => "$header \n $body \n $shortUrl" 
                ]);

                $sent = SentMessage::firstOrCreate([
                    'businessId' => $businessId,
                    'sendToType' => $sendToTypes,
                ]);
                
                $sent->timesSent++;
                $sent->save();

                return response()->json(['message' => 'Review invite sent!']);
            } else if($sendToTypes === 'Review Invite' && $reviewerNo === null) {
                return response()->json(['error' => 'No recipient phone number provided for reviewer'], 400);
            }

            // (getenv('APP_ENV') === 'local') ? $recipientNos = ["+14352224432"] : self::getRecipients($sendToTypes);
            $recipientNos = (getenv('APP_ENV') === 'local') ? ["+14352224432"] : null;
            if ($recipientNos === null) return;
            
            foreach($recipientNos as $recipientNo)
            {
                if(!empty(Subscriber::where(['phoneNumber' => $reviewerNo, 'businessId' => $businessId, 'subscribed' => 1]))) continue;
                // \Log::info("in loop");
                $shortUrl = !Url::where('fullUrl', $url)->exists() ? self::handleNewUrl($url, $recipientNo) : Url::where('fullUrl', $url)->get()->shortUrl;

                $client->messages->create($recipientNo, [
                    'from' => $twilio_num,
                    'body' => $header.'\n\n'.$body.'\n'.$shortUrl
                ]);
            }
            

            return response()->json(['message' => 'Successfully sent message']);
        }
        catch (\Exception $e) {
            return response()->json(['error' => $e->getMessage()]);
        }
    }

    /**
     * @param $sendToType, a key for SendToType table/model
     * 
     * @return array of recipient phone no.s to be iterated in send method
     */
    public static function getRecipients(mixed $sendToType) : array
    {
        // if ($sendToType)
    }



    // public static function create() : Client
    // {
    //     $twilSid = env('TWILIO_SENDER_NO');
    //     $twilToken = env('TWILIO_AUTH_TOKEN');

    //     $client = new Client($twilSid, $twilToken);
    //     return $client;
    // }

    // public static function send(string $recipientNo, mixed $meta) 
    // {
    //     // $recipientNo = env('TWILIO_PHONE_NO');
    //     try 
    //     {
    //         $client->messages->create(
    //             $senderNo,
    //             $meta
    //         );
    //     }
    //     catch (\Exception $e) {
    //         return response()->json(['error' => $e->getMessage(), 400]);
    //     }
        
    // }

    public function get()
    {
        //
    }

    public function read()
    {
        //
    }

    /**
     * Creates a new Url to be used in message
     * @param string $fullUrl
     * @param string $customerPhoneNo
     * 
     * @return String $shortUrl
     */
    private static function handleNewUrl(string $fullUrl, $customerPhoneNo) : String
    {
        $shortUrl = GenerateReviewUrlService::generate();
        // $shortUrl = $this->genReview->generate(); // Generate new Short URL
        $subscriber = json_decode(Subscriber::where('phoneNumber', $customerPhoneNo)->get());
        \Log::info($subscriber);
        $subscriberId = $subscriber[0]->id;
        \Log::info($subscriberId);

        Url::create([
            'businessId' => \Auth::user()->businessId,
            'subscriberId' => $subscriberId,
            'fullUrl' => $fullUrl,
            'shortUrl' => $shortUrl,
        ]);

        return $shortUrl;
    }
}