# FROM nginx:1.21
FROM nginx:1.21

# COPY --chown=www-data:www-data . /var/www/html/
COPY vhost.conf /etc/nginx/conf.d/default.conf

RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

# FROM php:8.0-fpm

# RUN apt-get update && apt-get install -y \
#     libfreetype6-dev \
#     libjpeg-dev \
#     libpng-dev \
#     libwebp-dev \
#     --no-install-recommends \
#     && docker-php-ext-configure gd --with-freetype --with-jpeg \
#     && docker-php-ext-install pdo_mysql -j$(nproc) gd

# rm /var/www/html/Dockerfile.cronjob && \
#     rm /var/www/html/Dockerfile.btcnt && \
#     rm /var/www/html/README.md && \
#     usermod -u 1000 www-data && groupmod -g 1000 www-data && \
#     mkdir -p storage/logs && touch storage/logs/laravel.log && chmod -R 777 && \
    # bash /var/www/html/k8s/docker/nodejs_v15.sh && \
    # apt-get install -y nodejs

